swagger: "2.0"
info:
  description: "API pública para la consulta de casos de coronavirus en la Argentina"
  version: "0.1.0"
  title: "ArCovidAPI"
  contact:
    email: "hackerfun@hackerfun.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "covidapi.hackfunrosario.com"
basePath: "/api"
schemes:
- "https"
paths:
  /stats:
    post:
      tags:
      - "stats"
      summary: "Agregar una estadística a la base de datos"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      security:
        - bearerAuth: []
      parameters:
      - in: "body"
        name: "body"
        description: "Información que será agregada a la base de datos"
        required: true
        schema:
          $ref: "#/definitions/InputStat"
      responses:
        201:
          description: "Dato guardado correctamente"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                example: "true"
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Stat"
        400:
          description: "Datos Inválidos o inexistentes; error al guardar en la base"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                default: "false"
              error:
                type: "string"
                example: "Es necesario cargar los datos para guardar."
  /stats/{page}:
    get:
      tags:
      - "stats"
      summary: "Obtener las estadísticas existentes"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - $ref: '#/parameters/pageParam'
        - $ref: '#/parameters/limiteParam'
        - $ref: '#/parameters/fechaDesdeParam'
        - $ref: '#/parameters/fechaHastaParam'
      responses:
        200:
          description: "Devuelve todas las estadísticas de la base de datos"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                default: "true"
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Stat"
        400:
          description: "Error al consultar la base de datos"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                default: "false"
              error:
                type: "string"
                example: "error"
  /getStatByProvincia/{provincia}/{page}:
    get:
      tags:
      - "stats"
      summary: "Buscar estadísticas por provincia"
      produces:
      - "application/json"
      parameters:
      - name: "provincia"
        in: "path"
        description: "Provincia a consultar"
        required: true
        type: "string"
        enum:
          - "Buenos Aires"
          - "CABA"
          - "Catamarca"
          - "Chaco"
          - "Chubut"
          - "Córdoba"
          - "Corrientes"
          - "Entre Ríos"
          - "Formosa"
          - "Jujuy"
          - "La Pampa"
          - "La Rioja"
          - "Mendoza"
          - "Misiones"
          - "Neuquén"
          - "Río Negro"
          - "Salta"
          - "San Juan"
          - "San Luis"
          - "Santa Cruz"
          - "Santa Fe"
          - "Santiago del Estero"
          - "Tierra del Fuego"
          - "Tucumán"
      - $ref: '#/parameters/pageParam'
      - $ref: '#/parameters/limiteParam'
      - $ref: '#/parameters/fechaDesdeParam'
      - $ref: '#/parameters/fechaHastaParam'
      responses:
        200:
          description: "Todos los datos de una provincia"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                default: "true"
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Stat"
        400:
          description: "Error al consultar la base de datos"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                default: "false"
              error:
                type: "string"
                example: "error"
  /getStatByFecha/{fecha}/{page}:
    get:
      tags:
      - "stats"
      summary: "Buscar estadísticas por fecha"
      produces:
      - "application/json"
      parameters:
      - name: "fecha"
        in: "path"
        description: "Fecha a consultar, en formato RFC3339 §5.6"
        required: true
        type: "string"
      - $ref: '#/parameters/pageParam'
      - $ref: '#/parameters/limiteParam'
      responses:
        200:
          description: "Todos los datos de una fecha"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                default: "true"
              data:
                type: "array"
                items:
                  $ref: "#/definitions/Stat"
        400:
          description: "Error al consultar la base de datos"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                default: "false"
              error:
                type: "string"
                example: "error"
  /auth/registerUser:
    post:
      tags:
      - "auth"
      summary: "Registro de un usuario nuevo"
      produces:
      - "application/json"
      parameters:
      - name: "admin-key"
        in: "header"
        type: "string"
        required: true
        description: "Admin Key necesaria para crear usuarios"
      - name: "body"
        in: "body"
        schema:
          type: "object"
          properties:
            username:
              type: "string"
            email:
              type: "string"
            password:
              type: "string"
            name:
              type: "string"
            admin:
              type: "boolean"              
      responses:
        200:
          description: "JWT Token"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                default: "true"
              data:
                type: "object"
                example: "Usuario creado"
        400:
          description: "Datos inválidos"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                default: "false"
              error:
                type: "string"
                example: "Es necesario cargar los datos para guardar."
        403:
          description: "No tiene permisos para crear usuarios"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                default: false
              error:
                type: "string"
                default: "Forbidden"
  /auth/signIn:
    post:
      tags:
      - "auth"
      summary: "Logueo de un usuario"
      produces:
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        schema:
          type: "object"
          properties:
            username:
              type: "string"
            password:
              type: "string"
      responses:
        200:
          description: "JWT Token"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                default: "true"
              token:
                type: "string"
              expire:
                type: "integer"
                example: "1440"
        403:
          description: "Datos inválidos"
          schema:
            type: "object"
            properties:
              success:
                type: "boolean"
                default: "false"
              error:
                type: "string"
                default: "Forbidden"
parameters:
  pageParam:
    in: "path"
    required: true
    name: "page"
    type: "integer"
    default: 0
    description: "(Opcional) Número de página para ser mostrado."      
  limiteParam:
    name: "limite"
    in: "query"
    type: "integer"
    required: false
    default: 25
    description: "Cantidad de registros por página que devuelve la consulta. Se pueden devolver todos los registros disponibles en una sola página estableciendo limite = -1."
  fechaDesdeParam:
    name: "fechaDesde"
    in: "query"
    type: "string"
    required: false
    description: "Si se establece, la consulta sólo devuelve registros posteriores a esta fecha. En formato RFC3339 §5.6"
  fechaHastaParam:
    name: "fechaHasta"
    in: "query"
    type: "string"
    required: false
    description: "Si se establece, la consulta sólo devuelve registros anteriores a esta fecha. En formato RFC3339 §5.6"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
        description: "Nombre"
      lastName:
        type: "string"
        description: "Apellido"
      email:
        type: "string"
        format: "email"
        description: "Correo del usuario"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "Estado del usuario"
    xml:
      name: "User"
  InputStat:
    type: "object"
    properties:
      fecha:
        type: "string"
        example: "2020-03-19T00:00:00.000Z"
      provincia:
        type: "string"
        example: "Santa Fe"
      ciudad:
        type: "string"
        example: "Rosario"
      departamento:
        type: "string"
        example: "Rosario"
      zona:
        type: "string"
        example: "Litoral"            
      confirmados_total:
        type: "integer"
        example: "12"
        format: "int32"
        description: "Total de confirmados al día de la fecha"
      confirmados_dif:
        type: "integer"
        example: "12"
        format: "int32"
        description: "Diferencial de confirmados entre el último reporte y el actual"        
      muertes_total:
        type: "integer"
        example: "2"
        format: "int32"
        description: "Total de muertes al día de la fecha"        
      muertes_dif:
        type: "integer"
        example: "12"
        format: "int32"
        description: "Diferencial de muertes entre el último reporte y el actual"        
      recuperados_total:
        type: "integer"
        example: "2"
        format: "int32"
        description: "Total de recuperados al día de la fecha"        
      recuperados_dif:
        type: "integer"
        example: "12"
        format: "int32"
        description: "Diferencial de recuperados entre el último reporte y el actual"        
      url:
        type: "string"
        example: "https://www.argentina.gob.ar/sites/default/files/22-03-20-reporte-diario_covid19.pdf"
  Stat:
    type: "object"
    properties:
      _id:
        type: "string"
        example: "5e77787d9d388471919abc70"
        description: "Id del registro"
      fecha:
        type: "string"
        example: "2020-03-19T00:00:00.000Z"
        description: "Fecha del registro, en formato RFC3339 §5.6"
      timestamp:
        type: "integer"
        example: "1584586800"
        description: "Fecha del registro en formato timestamp"
      provincia:
        type: "string"
        example: "Santa Fe"
      ciudad:
        type: "string"
        example: "Rosario"
      departamento:
        type: "string"
        example: "Rosario"
      zona:
        type: "string"
        example: "Litoral"        
      confirmados_total:
        type: "integer"
        example: "12"
        format: "int32"
        description: "Total de confirmados al día de la fecha"
      confirmados_dif:
        type: "integer"
        example: "12"
        format: "int32"
        description: "Diferencial de confirmados entre el último reporte y el actual"        
      muertes_total:
        type: "integer"
        example: "2"
        format: "int32"
        description: "Total de muertes al día de la fecha"        
      muertes_dif:
        type: "integer"
        example: "12"
        format: "int32"
        description: "Diferencial de muertes entre el último reporte y el actual"        
      recuperados_total:
        type: "integer"
        example: "2"
        format: "int32"
        description: "Total de recuperados al día de la fecha"        
      recuperados_dif:
        type: "integer"
        example: "12"
        format: "int32"
        description: "Diferencial de recuperados entre el último reporte y el actual"        
      url:
        type: "string"
        example: "https://www.argentina.gob.ar/sites/default/files/22-03-20-reporte-diario_covid19.pdf"
      userId:
        type: "string"
        example: "5e776d97f097d3027803bb1c"
        description: "Id del usuario que cargó la estadística"
      createdAt:
        type: "string"
        example: "2020-03-22T14:38:53.524Z"
        description: "Fecha de creación del registro, en formato RFC3339 §5.6"
      updatedAt:
        type: "string"
        example: "2020-03-22T14:38:53.524Z"
        description: "Fecha de actualización del registro, en formato RFC3339 §5.6"
        
securityDefinitions:
  bearerAuth:
    type: "apiKey"
    in: "header"
    name: "Authorization"
      
